### ISSUE TITLE
double cast by dpct

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/cuda-to-sycl-nbody#26]
I tried the DPCT tool from Syclomatic. It does not generate the cast...

```
sycl::rsqrt((double)dist_sqr * dist_sqr * dist_sqr);
```

**Comment by DuncanMcBain** [comment]
Hi @jinz2014,

If I understand you correctly, the original CUDA code effectively calls `rsqrt(double)` even though `coords_t` is `float`, and you would therefore expect that the translation tool should respect that and cast the intermediate result to make sure the right function is being called.

I think your best bet is to make an issue in the Syclomatic repository as I don't think this is necessarily related to the code in this repository specifically.

**Comment by jinz2014** [comment]
Thank you for your reply. I'll close the issue.
